import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import { useTheme } from "next-themes";
import { useEffect, useState } from "react";
import CatalogCard from "../components/CatalogCard";

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { resolvedTheme, setTheme } = useTheme();

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <>
      <div className="bg-gray-50 dark:bg-gray-900">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className=" flex justify-center flex-col px-8">
          <nav className=" flex items-center justify-between w-full relative max-w-2xl border-gray-200 dark:border-gray-700 mx-auto pt-8 pb-8 text-gray-900 bg-gray-50  dark:bg-gray-900 bg-opacity-60 dark:text-gray-100">
            <Link
              href={"/"}
              className="font-semibold text-gray-800 dark:text-gray-200 hidden md:inline-block p-1 sm:px-3 sm:py-2 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-800 transition-all"
            >
              <span>Three Js Stuff</span>
            </Link>
            <button
              aria-label="Toggle Dark Mode"
              type="button"
              className=" w-9 h-9 bg-gray-200 rounded-lg dark:bg-gray-600 flex items-center justify-center hover:ring-2 ring-gray-300 transition-all"
              onClick={() => {
                setTheme(resolvedTheme === "dark" ? "light" : "dark");
              }}
            >
              {mounted && (
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  className="w-5 h-5 text-gray-800 dark:text-gray-200"
                >
                  {resolvedTheme === "dark" ? (
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
                    />
                  ) : (
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"
                    />
                  )}
                </svg>
              )}
            </button>
          </nav>
        </div>
        <main className="bg-gray-50 dark:bg-gray-900 flex flex-col justify-center px-8">
          <div className="flex flex-col justify-center items-start max-w-2xl border-gray-200 dark:border-gray-700 mx-auto pb-16">

            <div className="flex flex-col items-start mb-8">
              <div className="py-4">
                <h1 className="font-bold text-3xl md:text-5xl tracking-tight text-black dark:text-white">
                  Hello There!
                </h1>
              </div>
              <p className="text-gray-600 dark:text-gray-400 mb-4">
                After some time figuring out how Three Js, I now create this site, where
                I dump my ThreeJs creations for the world to see.
                <br />
                <br/>
                This place also serves as a testing ground for nextJs, Tailwind and Framer Motion.
              </p>
              <div className="flex flex-row w-full color">
                <div className="flex-grow-[1] p-2 font-semibold">
                    Stack:
                </div>
                <div className="flex-grow-[3] p-2">
                    React, Framer Motion, ThreeJs, TailwindCSS
                </div>
              </div>
            </div>

            <h3 className="font-bold text-2xl md:text-4xl tracking-tight mb-6 text-black dark:text-white">
              Catalog
            </h3>
            <div className="w-full max-w-2xl grid grid-cols-1 sm:grid-cols-3 gap-3">
              <CatalogCard /> 
            </div>

          </div>
        </main>
      </div>
    </>
  );
}
